---
- name: Deploy Biostar codebase
  hosts: biostarhosts
  gather_facts: False
  user: ubuntu

  # Those vars are here (instead of being in a default dir in a role) because they are shared
  # between the docker_postgresql and the docker_webapp role.
  vars:
    postgresql_username: biostar
    postgresql_password: biostar
    # The following paths must be full paths (no '~').
    host_dir_for_codebase: /srv/biostar-codebase
    host_dir_for_dockerfiles: /srv/dockerfiles
    host_dir_for_dockervolumes: /srv/docker-volumes
    container_dir_for_codebase: /srv/biostar

  roles:
    - docker_postgresql
    - docker_webapp